[project]
name = "Seq2Phase"
version = "0.1.0"
description = "Handeling the dependencies of Seq2Phase"
channels = ["conda-forge", "bioconda", "Pypi"]
platforms = ["linux-64"]

[tasks]
build_train = {cmd = "python train_model.py"}
evaluate_seq2phase = {cmd = "python seq2phase.py -d ./model/"}

[dependencies]
bio-embeddings = ">=0.2.2,<0.3"
pytorch = "1.10.0"
pyyaml = "5.1"
python = ">=3.7.12,<3.8"
transformers = ">=4.19.4,<4.20"
torchvision = ">=0.11.2,<0.12"
sentencepiece = ">=0.1.96,<0.2"
